/**
 * Balde de placeholders do composer para os modelos IAzzas (Flash/Pro).
 * Um é sorteado por montagem do chat — dá sensação de frescor a cada visita
 * sem rotação em tela (respeita o "zero atrito" do design). Mistura convites,
 * dicas de capacidade (ensinam o que o IAzzas faz) e contexto de moda/varejo.
 */
export const composerPlaceholders: string[] = [
  'No que vamos trabalhar hoje?',
  'Como posso ajudar?',
  'Manda sua pergunta…',
  'Por onde começamos?',
  'Conta o que você precisa.',
  'O que você precisa resolver agora?',
  'Qual é a missão de hoje?',
  'Descreva o que você quer criar',
  'Comece escrevendo sua ideia',
  'Peça uma análise das vendas da semana',
  'Compare o estoque entre as marcas',
  'Resuma um relatório em poucos pontos',
  'Pergunte sobre o desempenho de uma coleção',
  'Peça os destaques de vendas por loja',
  'Analise uma planilha de estoque',
  'Compare o giro de produtos por categoria',
  'Peça um comparativo entre duas coleções',
  'Resuma os principais números do mês',
  'Escreva um texto para a campanha',
  'Crie uma legenda para o post',
  'Revise um texto rapidinho',
  'Peça o resumo daquele PDF',
  'Gere ideias para a próxima coleção',
  'Traduza um texto para outro idioma',
  'Monte um e-mail para o time',
  'Transforme suas notas em um resumo',
  'Quer um texto pronto? Descreva a ideia',
  'Gere uma imagem para a campanha',
  'Crie um moodboard de inspiração',
  'Peça uma arte para o feed',
  'Pesquise uma tendência de moda',
  'Busque referências para um briefing',
  'Pergunte o que está em alta na estação',
  'Organize as ideias de uma reunião',
  'Monte um checklist para o lançamento',
  'Peça um rascunho de apresentação',
  'Planeje as etapas de um projeto',
  'Pergunte sobre as marcas do grupo',
  'Explore os dados de uma campanha',
  'Peça uma leitura do público de uma marca',
];
